# Generated by Django 5.1.4 on 2025-01-17 14:18

import apps.VideoCourse.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='slug')),
                ('last_update_date', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория видео',
                'verbose_name_plural': 'Категории видео',
            },
        ),
        migrations.CreateModel(
            name='TestContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Вопрос в текстовом формате')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Вопрос в файловом формате')),
                ('var_A_image', models.ImageField(blank=True, null=True, upload_to=apps.VideoCourse.models.upload_to_test, verbose_name="Вариант ответа 'A' (В файловом варианте)")),
                ('var_B_image', models.ImageField(blank=True, null=True, upload_to=apps.VideoCourse.models.upload_to_test, verbose_name="Вариант ответа 'B' (В файловом варианте)")),
                ('var_C_image', models.ImageField(blank=True, null=True, upload_to=apps.VideoCourse.models.upload_to_test, verbose_name="Вариант ответа 'C' (В файловом варианте)")),
                ('var_D_image', models.ImageField(blank=True, null=True, upload_to=apps.VideoCourse.models.upload_to_test, verbose_name="Вариант ответа 'D' (В файловом варианте)")),
                ('var_A_text', models.TextField(blank=True, null=True, verbose_name="Вариант ответа 'A' (В текстовом варианте)")),
                ('var_B_text', models.TextField(blank=True, null=True, verbose_name="Вариант ответа 'B' (В текстовом варианте)")),
                ('var_C_text', models.TextField(blank=True, null=True, verbose_name="Вариант ответа 'C' (В текстовом варианте)")),
                ('var_D_text', models.TextField(blank=True, null=True, verbose_name="Вариант ответа 'D' (В текстовом варианте)")),
                ('true_answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=10, verbose_name='Правильный ответ')),
                ('test_order', models.PositiveIntegerField(unique=True, verbose_name='Порядковый номер')),
                ('last_update_date', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Вопрос теста',
                'verbose_name_plural': 'Вопросы тестов',
                'ordering': ['test_order'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_vars', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1, verbose_name='Ответ')),
                ('output_time', models.PositiveIntegerField(default=1, verbose_name='Время ответа (в секундах)')),
                ('last_update_date', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('test_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoCourse.testcontent', verbose_name='Тест контент')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answer_videocourse', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100, verbose_name='Название тема урока')),
                ('description', models.TextField(verbose_name='Описание темы урока')),
                ('video_url', models.TextField(verbose_name='Ссылка на видео')),
                ('video_order', models.PositiveIntegerField(unique=True, verbose_name='Порядковый номер')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Является ли видео платным?')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='slug')),
                ('last_update_date', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('video_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='VideoCourse.categoryvideo', verbose_name='Категория видео')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ['video_order'],
            },
        ),
        migrations.AddField(
            model_name='testcontent',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoCourse.video', verbose_name='Тест'),
        ),
        migrations.CreateModel(
            name='UserStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('true_answer_count', models.PositiveIntegerField(default=0, verbose_name='Количество правильных ответов')),
                ('false_answer_count', models.PositiveIntegerField(default=0, verbose_name='Количество неправильных ответов')),
                ('last_update_date', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statistics_videocourse', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoCourse.video', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Счет ответов',
                'verbose_name_plural': 'Счета ответов',
                'unique_together': {('video', 'user')},
            },
        ),
    ]
