# Generated by Django 5.1.4 on 2025-01-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoCourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatistic',
            name='accuracy_percentage',
            field=models.FloatField(default=0.0, verbose_name='Процент правильных ответов'),
        ),
    ]
