# Generated by Django 5.1.4 on 2025-01-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoCourse', '0002_userstatistic_accuracy_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcontent',
            name='additional_questions',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительный текст к вопросу'),
        ),
        migrations.AlterUniqueTogether(
            name='testcontent',
            unique_together={('video', 'test_order')},
        ),
    ]
