# Generated by Django 5.1.4 on 2025-01-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoCourse', '0003_testcontent_additional_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_order',
            field=models.PositiveIntegerField(verbose_name='Порядковый номер'),
        ),
    ]
