# Generated by Django 5.1.4 on 2025-01-18 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VideoCourse', '0004_alter_video_video_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryvideo',
            options={'verbose_name': 'Категория видео', 'verbose_name_plural': '1 Категории видео'},
        ),
        migrations.AlterModelOptions(
            name='testcontent',
            options={'ordering': ['test_order'], 'verbose_name': 'Вопрос теста', 'verbose_name_plural': '3 Вопросы тестов'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'Ответ пользователя', 'verbose_name_plural': '5 Ответы пользователей'},
        ),
        migrations.AlterModelOptions(
            name='userstatistic',
            options={'verbose_name': 'Счет ответов', 'verbose_name_plural': '4 Счета ответов'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['video_order'], 'verbose_name': 'Видео', 'verbose_name_plural': '2 Видео'},
        ),
    ]
