# Generated by Django 5.1.4 on 2025-01-23 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoCourse', '0005_alter_categoryvideo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_category_name', models.CharField(max_length=52, verbose_name='Название типа теста')),
                ('last_update_date', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория теста',
                'verbose_name_plural': '2. Категории тестов',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='subject_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VideoCourse.subjectcategory', verbose_name='Категория предмета'),
            preserve_default=False,
        ),
    ]
