# Generated by Django 5.1.4 on 2025-01-24 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VideoCourse", "0007_category_alter_categoryvideo_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subjectcategory",
            options={
                "verbose_name": "Под категория видео",
                "verbose_name_plural": "3. Под категории видео",
            },
        ),
        migrations.AddField(
            model_name="video",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="VideoCourse.category",
                verbose_name="Категория предмета",
            ),
        ),
        migrations.AlterField(
            model_name="subjectcategory",
            name="subject_category_name",
            field=models.CharField(max_length=52, verbose_name="Название типа видео"),
        ),
        migrations.AlterField(
            model_name="video",
            name="subject_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="VideoCourse.subjectcategory",
                verbose_name=" Предмета",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="VideoCourse.categoryvideo",
                verbose_name="Под категория предмета",
            ),
        ),
    ]
