# Generated by Django 5.1.4 on 2025-01-26 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VideoCourse', '0008_alter_subjectcategory_options_video_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryName',
            new_name='category_name',
        ),
    ]
