# Generated by Django 5.1.4 on 2025-02-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoCourse', '0010_testcontent_var_e_image_testcontent_var_e_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcontent',
            name='question_text',
            field=models.TextField(blank=True, null=True, verbose_name='Вопрос в текстовом формате'),
        ),
    ]
