# Generated by Django 5.1.4 on 2025-02-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoCourse', '0010_testcontent_var_e_image_testcontent_var_e_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcontent',
            options={'ordering': ['question_number'], 'verbose_name': 'Вопрос теста', 'verbose_name_plural': '5. Вопросы тестов в видео'},
        ),
        migrations.AlterUniqueTogether(
            name='testcontent',
            unique_together={('video', 'question_number')},
        ),
        migrations.AddField(
            model_name='testcontent',
            name='question_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядковый номер вопроса'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer_vars',
            field=models.CharField(choices=[('а', 'А'), ('б', 'Б'), ('в', 'В'), ('г', 'Г'), ('д', 'Д')], max_length=1, verbose_name='Ответ'),
        ),
        migrations.RemoveField(
            model_name='testcontent',
            name='test_order',
        ),
    ]
