# Generated by Django 5.1.4 on 2025-02-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoCourse', '0011_alter_testcontent_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answer_vars',
            field=models.CharField(choices=[('а', 'А'), ('б', 'Б'), ('в', 'В'), ('г', 'Г'), ('д', 'Д')], max_length=1, verbose_name='Ответ студента'),
        ),
    ]
