# Generated by Django 5.1.4 on 2025-02-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoCourse', '0012_alter_testcontent_question_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcontent',
            name='question_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядковый номер вопроса'),
        ),
    ]
