POST http://127.0.0.1:8000/api/v1/sign-up/
Content-Type: application/json

{
    "email": "ernistturgunbaev1@gmail.com",
    "password": "Adminpassword",
    "password_confirm": "Adminpassword",
    "user_status": "Студент",
    "first_name": "Ernisturacdsvi",
    "last_name": "Turgunbaev",
    "paid": "Оплачено"


}


###
POST http://127.0.0.1:8000/api/v1/token/
Content-Type: application/json

{
  "email": "ernistturgunbaev01@gmail.com",
  "password": "qwerty123"
}


###
GET http://127.0.0.1:8000/api/v1/videos/video/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1ODA5ODg2LCJpYXQiOjE3MzU4MDk1ODYsImp0aSI6Ijc3YzEzY2E1Y2ZmMzRmMmY5MjQxYThlMTMwZWMzNjc4IiwidXNlcl9pZCI6N30.kcpzPZU2dQHYH9AIWvQxQ4wd5Cb9-Jx_64B7a1THpHg



###
GET http://127.0.0.1:8000/api/v1/videos/video/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1ODA5ODg2LCJpYXQiOjE3MzU4MDk1ODYsImp0aSI6Ijc3YzEzY2E1Y2ZmMzRmMmY5MjQxYThlMTMwZWMzNjc4IiwidXNlcl9pZCI6N30.kcpzPZU2dQHYH9AIWvQxQ4wd5Cb9-Jx_64B7a1THpHg


###
GET  http://127.0.0.1:8000/api/v1/videos/test/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1ODA5ODg2LCJpYXQiOjE3MzU4MDk1ODYsImp0aSI6Ijc3YzEzY2E1Y2ZmMzRmMmY5MjQxYThlMTMwZWMzNjc4IiwidXNlcl9pZCI6N30.kcpzPZU2dQHYH9AIWvQxQ4wd5Cb9-Jx_64B7a1THpHg

###
GET http://127.0.0.1:8000/api/v1/videos/user-answers/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1ODE3ODgxLCJpYXQiOjE3MzU4MTc1ODEsImp0aSI6IjViOTkzY2I4MTQ1ZDRjOWNiNjdhMWM4MGU1MWQ5OTU3IiwidXNlcl9pZCI6N30.d5Uxp8C1dLQ-vIWGuIxIm419Bo52GlLhD74l4SViWHw