# Generated by Django 5.1.4 on 2025-01-04 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos_tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryvideo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Категория видео', 'verbose_name_plural': 'Категории видео'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at'], 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.RenameField(
            model_name='answeroption',
            old_name='createa_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='categoryvideo',
            old_name='created_data',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='createa_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='created_data',
            new_name='created_at',
        ),
    ]
