# Generated by Django 5.1.4 on 2025-01-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos_tests', '0002_alter_categoryvideo_options_alter_video_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnswerOption',
            new_name='AnswerOptionModel',
        ),
        migrations.RenameModel(
            old_name='CategoryVideo',
            new_name='CategoryVideoModel',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='QuestionModel',
        ),
        migrations.RenameModel(
            old_name='Video',
            new_name='VideoModel',
        ),
    ]
