# Generated by Django 5.1.4 on 2025-01-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_tests', '0003_rename_answeroption_answeroptionmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answeroptionmodel',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.RemoveField(
            model_name='answeroptionmodel',
            name='question',
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='options',
            field=models.ManyToManyField(related_name='options', to='videos_tests.answeroptionmodel'),
        ),
    ]
