# Generated by Django 5.1.4 on 2025-01-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_tests', '0004_alter_answeroptionmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodel',
            name='options',
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='option_A',
            field=models.CharField(default=1, max_length=200, verbose_name='Вариант A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='option_B',
            field=models.CharField(default=1, max_length=200, verbose_name='Вариант B'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='option_C',
            field=models.CharField(default=1, max_length=200, verbose_name='Вариант C'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='option_D',
            field=models.CharField(default=2, max_length=200, verbose_name='Вариант D'),
            preserve_default=False,
        ),
    ]
