# Generated by Django 5.1.4 on 2024-12-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbountUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='О нас')),
                ('image', models.ImageField(upload_to='aboutus/images', verbose_name='Фотография')),
            ],
        ),
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('image', models.ImageField(upload_to='graduates/images', verbose_name='Фотография')),
                ('grade', models.IntegerField(default=0, verbose_name='Оценка')),
                ('review', models.TextField(verbose_name='Отзыв')),
                ('created_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
