# Generated by Django 5.1.4 on 2025-01-11 06:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('gmail', models.EmailField(max_length=100, verbose_name='Gmail')),
                ('phone_number', models.CharField(max_length=55, validators=[django.core.validators.RegexValidator(message='Введите правильный номер телефона', regex='^(0\\d{9}|\\+996\\d{9})$')], verbose_name='Номер телефона')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('created_data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_data'],
            },
        ),
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('image', models.ImageField(upload_to='graduates/images', verbose_name='Фотография')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(245)], verbose_name='Баллы')),
                ('review', models.TextField(verbose_name='Отзыв')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('created_data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Выпускник',
                'verbose_name_plural': 'Выпускники',
                'ordering': ['-created_data'],
            },
        ),
        migrations.CreateModel(
            name='TeacherType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.teachertype')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['-created_data'],
            },
        ),
        migrations.CreateModel(
            name='AbountTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=55, verbose_name='Фамилия')),
                ('image', models.ImageField(upload_to='teachers/images', verbose_name='Фотография')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('teacher_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_type', to='core.teachertype')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['-created_data'],
            },
        ),
    ]
