# Generated by Django 5.1.4 on 2024-12-26 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbountTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=55, verbose_name='Фамилия')),
                ('teacher_type', models.CharField(max_length=55, verbose_name='Тип преподавателя')),
                ('image', models.ImageField(upload_to='teachers/images', verbose_name='Фотография')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('created_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('gmail', models.EmailField(max_length=100, verbose_name='Gmail')),
                ('phone_number', models.CharField(max_length=55, validators=[django.core.validators.RegexValidator(message='Введите правильный номер телефона', regex='^(0\\d{9}|\\+996\\d{9})$')], verbose_name='Номер телефона')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('created_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('image', models.ImageField(upload_to='graduates/images', verbose_name='Фотография')),
                ('score', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Баллы')),
                ('review', models.TextField(verbose_name='Отзыв')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('created_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
