# Generated by Django 5.1.4 on 2024-12-23 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('gmail', models.EmailField(max_length=100, verbose_name='Gmail')),
                ('phone_number', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Введите правильный номер телефона', regex='^\\+996\\d{9}$')], verbose_name='Номер телефона')),
            ],
        ),
    ]
