# Generated by Django 5.1.4 on 2024-12-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abountteacher',
            name='teacher_type',
            field=models.CharField(choices=[('математика', 'математика'), ('кыргыз ', 'кыргыз тил'), ('физика', 'физика'), ('химия', 'химия'), ('биология', 'биология'), ('тарых', 'тарых')], max_length=55, verbose_name='Тип преподавателя'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Баллы'),
        ),
    ]
