# Generated by Django 5.1.4 on 2025-01-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_abountteacher_teacher_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graduate",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, unique=True, verbose_name="URL"
            ),
        ),
    ]
