# Generated by Django 5.1.4 on 2024-12-24 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abountus',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='lastname',
            field=models.CharField(max_length=25, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone_number',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Введите правильный номер телефона', regex='^(0\\d{9} | \\+996\\d{9})$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='lastname',
            field=models.CharField(max_length=25, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Имя'),
        ),
    ]
