# Generated by Django 5.1.4 on 2024-12-24 15:10

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_abountus_title_alter_feedback_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abountus',
            name='mission',
            field=models.TextField(default=2, verbose_name='Что мы приложим'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abountus',
            name='our_goals',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Что мы хотим достичь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abountus',
            name='our_team',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Кратко о нашей команде'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone_number',
            field=models.CharField(max_length=55, validators=[django.core.validators.RegexValidator(message='Введите правильный номер телефона', regex='^(0\\d{9}|\\+996\\d{9})$')], verbose_name='Номер телефона'),
        ),
    ]
