# Generated by Django 5.1.4 on 2025-01-10 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL')),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='videos.categoryvideo', verbose_name='Подкатегория видео (Математика)')),
            ],
            options={
                'verbose_name': 'Категория видео',
                'verbose_name_plural': 'Категории видео',
                'db_table': 'category_video',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Название тема урока')),
                ('description', models.TextField(verbose_name='Описание темы урока')),
                ('video_url', models.TextField(verbose_name='Ссылка на видео')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Является ли видео платным?')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL')),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='videos.categoryvideo', verbose_name='Категория видео')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст вопроса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='Изображение вопроса')),
                ('image_a', models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='Изображение варианта A')),
                ('answer_a', models.TextField(blank=True, max_length=255, null=True, verbose_name='Вариянт A')),
                ('image_b', models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='Изображение варианта B')),
                ('answer_b', models.TextField(blank=True, max_length=255, null=True, verbose_name='Вариянт B')),
                ('image_c', models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='Изображение варианта C')),
                ('answer_c', models.TextField(blank=True, max_length=255, null=True, verbose_name='Вариянт C')),
                ('image_d', models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='Изображение варианта D')),
                ('answer_d', models.TextField(blank=True, max_length=255, null=True, verbose_name='Вариянт D')),
                ('is_correct', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Правилный ответ')),
                ('is_paid', models.BooleanField(verbose_name='Является ли тест платным?')),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='videos.video', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['-video'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField(default=0, verbose_name='Всего вопросов')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='Всего правильных ответов')),
                ('incorrect_answers', models.IntegerField(default=0, verbose_name='Всего неправильных ответов')),
                ('result_percentage', models.FloatField(default=0, verbose_name='Результат теста')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL')),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('passed', models.BooleanField(default=False, verbose_name='Пройден')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='videos.video')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
                'ordering': ['-created_data'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Ответ на вопрос')),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='videos.test')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['-student', '-created_data'],
                'unique_together': {('question', 'student')},
            },
        ),
    ]
