# Generated by Django 5.1.4 on 2024-12-29 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL')),
                ('created_data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'category_video',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_question', models.IntegerField(verbose_name='Номер вопроса')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('answer_a', models.TextField(blank=True, max_length=1, null=True, verbose_name='Ответ на вопрос')),
                ('answer_b', models.TextField(blank=True, max_length=1, null=True, verbose_name='Ответ на вопрос')),
                ('answer_c', models.TextField(blank=True, max_length=1, null=True, verbose_name='Ответ на вопрос')),
                ('answet_d', models.TextField(blank=True, max_length=1, null=True, verbose_name='Ответ на вопрос')),
                ('is_correct', models.CharField(choices=[('A', 'A'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г')], max_length=1, verbose_name='Правилный ответ')),
                ('created_data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=255, verbose_name='Результат теста')),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='videos.test')),
            ],
            options={
                'db_table': 'result',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('A', 'A'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г')], max_length=1, verbose_name='Ответ на вопрос')),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_answer',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Название тема урока')),
                ('description', models.TextField(verbose_name='Описание темы урока')),
                ('video_url', models.URLField(max_length=100, verbose_name='Ссылка на видео')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Является ли видео платным?')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL')),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='videos.categoryvideo')),
            ],
            options={
                'db_table': 'video',
            },
        ),
        migrations.AddField(
            model_name='test',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='videos.video'),
        ),
    ]
