# Generated by Django 5.1.4 on 2024-12-29 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='qiestion',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='videos.test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_a',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Вариянт А'),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_b',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Вариянт Б'),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_c',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Вариянт В'),
        ),
        migrations.AlterField(
            model_name='test',
            name='answet_d',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Вариянт Г'),
        ),
    ]
