# Generated by Django 5.1.4 on 2025-01-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_result_options_result_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryvideo',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
