# Generated by Django 5.1.4 on 2024-12-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_useranswer_qiestion_alter_test_answer_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Является ли тест платным?'),
        ),
    ]
