# Generated by Django 5.1.4 on 2024-12-30 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_test_is_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='qiestion',
            new_name='question',
        ),
    ]
