# Generated by Django 5.1.4 on 2025-01-02 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_rename_answet_d_test_answer_d_remove_result_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryvideo',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='videos.categoryvideo'),
        ),
    ]
