# Generated by Django 5.1.4 on 2025-01-09 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_result_options_alter_useranswer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryvideo',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='categoryvideo',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='videos.categoryvideo', verbose_name='Подкатегория видео (Математика)'),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_a',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Вариянт A'),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_b',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Вариянт B'),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_c',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Вариянт C'),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_d',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Вариянт D'),
        ),
        migrations.AlterField(
            model_name='test',
            name='image_a',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='Изображение варианта A'),
        ),
        migrations.AlterField(
            model_name='test',
            name='image_b',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='Изображение варианта B'),
        ),
        migrations.AlterField(
            model_name='test',
            name='image_c',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='Изображение варианта C'),
        ),
        migrations.AlterField(
            model_name='test',
            name='image_d',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='Изображение варианта D'),
        ),
        migrations.AlterField(
            model_name='test',
            name='is_correct',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Правилный ответ'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Ответ на вопрос'),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='videos.categoryvideo', verbose_name='Категория видео'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.TextField(verbose_name='Ссылка на видео'),
        ),
    ]
