# Generated by Django 5.1.4 on 2025-01-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_remove_test_id_question_test_image_alter_test_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='Изображение вопроса'),
        ),
    ]
