# Generated by Django 5.1.4 on 2025-01-09 17:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_alter_categoryvideo_name_alter_categoryvideo_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterModelTable(
            name='categoryvideo',
            table='category_video',
        ),
    ]
