# Generated by Django 5.1.4 on 2025-01-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('bank', models.CharField(choices=[('MBANK', 'MBank'), ('OBANK', 'O!Bank'), ('ELDIK', 'Элдик Банк')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_service_name', models.CharField(max_length=100)),
                ('service_logo', models.ImageField(blank=True, null=True, upload_to='payments_service_logos/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='payment_qr_codes/')),
                ('req_number', models.CharField(blank=True, max_length=30, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
