# Generated by Django 5.1.4 on 2025-01-08 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_service_name', models.CharField(max_length=100, verbose_name='Названия сервиса')),
                ('service_logo', models.ImageField(blank=True, null=True, upload_to='payments_service_logos/', verbose_name='Логотип сервиса')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='payment_qr_codes/', verbose_name='QR код для оплаты')),
                ('prop_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер реквезита')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя Владельца карты')),
                ('whatsapp_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на WhatsApp')),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentservice', verbose_name='Сервис для оплаты'),
        ),
    ]
