# Generated by Django 5.1.4 on 2025-01-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_options_alter_paymentservice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True, verbose_name='slug'),
        ),
    ]
