# Generated by Django 5.1.4 on 2025-01-10 17:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailconfirmation',
            options={'verbose_name': 'Код активации Аккаунта', 'verbose_name_plural': 'Коды активации Аккаунтов'},
        ),
        migrations.AddField(
            model_name='mockassessmenttest',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
