# Generated by Django 5.1.4 on 2025-01-01 16:19

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MockAssessmentTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Введите корректный номер телефона",
                                regex="^\\+?1?\\d{9,13}$",
                            )
                        ],
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Пробная запись на оценочный тест",
                "verbose_name_plural": "Пробные записи на оценочные тесты",
            },
        ),
        migrations.RenameField(
            model_name="user",
            old_name="admin",
            new_name="is_status_approved",
        ),
        migrations.RemoveField(
            model_name="user",
            name="manager",
        ),
        migrations.RemoveField(
            model_name="user",
            name="student",
        ),
        migrations.RemoveField(
            model_name="user",
            name="teacher",
        ),
        migrations.AddField(
            model_name="emailconfirmation",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Введите корректный номер телефона",
                        regex="^\\+?1?\\d{9,13}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="paid",
            field=models.CharField(
                choices=[("Не оплачено", "Не оплачено"), ("Оплачено", "Оплачено")],
                default="Не оплачено",
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_status",
            field=models.CharField(
                choices=[
                    ("Менеджер", "Менеджер"),
                    ("Студент", "Студент"),
                    ("Мугалим", "Мугалим"),
                    ("Админ", "Админ"),
                ],
                default="Студент",
                max_length=10,
            ),
        ),
    ]
