# Generated by Django 5.1.4 on 2024-12-25 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_admin_user_is_status_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='^\\+?1?\\d{9,13}$')]),
        ),
    ]
