# Generated by Django 5.1.4 on 2025-01-09 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_mockassessmenttest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mockassessmenttest",
            name="last_update_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата последнего обновления"
            ),
        ),
        migrations.AlterField(
            model_name="mockassessmenttest",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="mockassessmenttest",
            name="last_name",
            field=models.CharField(max_length=50, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="mockassessmenttest",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Введите корректный номер телефона",
                        regex="^\\+?1?\\d{9,13}$",
                    )
                ],
                verbose_name="Номер телефона",
            ),
        ),
    ]
