# Generated by Django 5.1.4 on 2025-01-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.CharField(choices=[('Менеджер', 'Менеджер'), ('Студент', 'Студент'), ('Учитель', 'Учитель'), ('Админ', 'Админ')], default='Студент', max_length=10),
        ),
    ]
