# Generated by Django 5.1.4 on 2024-12-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfirmation',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
