# Generated by Django 5.1.4 on 2025-02-03 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.CharField(choices=[('Менеджер', 'Менеджер'), ('Студент', 'Студент'), ('Пользователь', 'Пользователь'), ('Админ', 'Админ')], default='Пользователь', max_length=12),
        ),
        migrations.CreateModel(
            name='MockAssessmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('answer', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.mockassessmenttest')),
            ],
            options={
                'verbose_name': 'Ответ на пробный тест',
                'verbose_name_plural': 'Ответы на пробные тесты',
            },
        ),
    ]
