# Generated by Django 5.1.4 on 2024-12-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailconfirmation_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='paid',
            field=models.CharField(choices=[('Не оплачено', 'Не оплачено'), ('Оплачено', 'Оплачено')], default='Не оплачено', max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.CharField(choices=[('Менеджер', 'Менеджер'), ('Студент', 'Студент'), ('Мугалим', 'Мугалим'), ('Админ', 'Админ')], default='Студент', max_length=10),
        ),
    ]
