# Generated by Django 5.1.4 on 2025-02-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_user_status_mockassessmentanswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MockAssessmentAnswer',
        ),
        migrations.DeleteModel(
            name='MockAssessmentTest',
        ),
    ]
