# Generated by Django 5.1.4 on 2025-02-05 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_mockassessmentanswer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
