# Generated by Django 5.1.4 on 2024-12-29 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_mockassessmenttest_user_date_joined_user_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MockAssessmentTest',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
