# Generated by Django 5.1.4 on 2025-01-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_date_joined_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_test_passed',
            field=models.BooleanField(default=False),
        ),
    ]
