# Generated by Django 5.1.4 on 2025-01-02 20:40

import apps.OrtTest.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_category_name', models.CharField(max_length=52, verbose_name='Название типа теста')),
            ],
            options={
                'verbose_name': 'Категория теста',
                'verbose_name_plural': 'Категории тестов',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название теста')),
                ('description', models.TextField(verbose_name='Описание теста')),
                ('background_image', models.ImageField(upload_to='test_background_image/', verbose_name='Фоновое изображение')),
                ('test_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrtTest.testcategory', verbose_name='Категория теста')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_test', models.BooleanField(default=False, verbose_name='Обозночение бедет ли тест первым бесплатным тестом')),
                ('var_A', models.ImageField(upload_to=apps.OrtTest.models.upload_to_test, verbose_name="Вариант ответа 'А'")),
                ('var_B', models.ImageField(upload_to=apps.OrtTest.models.upload_to_test, verbose_name="Вариант ответа 'Б'")),
                ('var_C', models.ImageField(upload_to=apps.OrtTest.models.upload_to_test, verbose_name="Вариант ответа 'В'")),
                ('var_D', models.ImageField(upload_to=apps.OrtTest.models.upload_to_test, verbose_name="Вариант ответа 'Г'")),
                ('true_answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=10, verbose_name='Правельный ответ')),
                ('timer', models.PositiveIntegerField(verbose_name='Таймер (в секундах)')),
                ('response_status', models.BooleanField(verbose_name='Статус ответа (true если правельный ответ)')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrtTest.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Данные теста',
                'verbose_name_plural': 'Данные теста',
            },
        ),
        migrations.CreateModel(
            name='TestFullDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_title', models.CharField(max_length=60, verbose_name='Название описания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('test_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrtTest.testcategory', verbose_name='Категория теста')),
            ],
            options={
                'verbose_name': 'Подробно описание теста',
                'verbose_name_plural': 'Подробные описании тестов',
            },
        ),
        migrations.CreateModel(
            name='TestInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_title', models.CharField(max_length=60, verbose_name='Название инструкции')),
                ('instruction', models.TextField(verbose_name='Инструкция')),
                ('test_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrtTest.testcategory', verbose_name='Категория теста')),
            ],
            options={
                'verbose_name': 'Инструкция теста',
                'verbose_name_plural': 'Инструкции тестов',
            },
        ),
        migrations.CreateModel(
            name='AdditionalInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_title', models.CharField(max_length=40, verbose_name='Название дополнительной инструкции')),
                ('additional_description', models.TextField(verbose_name='Описание дополнительной инструкции')),
                ('testing_instruction_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrtTest.testinstruction', verbose_name='Инструкция теста')),
            ],
            options={
                'verbose_name': 'Дополнительная инструкция',
                'verbose_name_plural': 'Дополнительные инструкции',
            },
        ),
    ]
