# Generated by Django 5.1.4 on 2025-01-23 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrtTest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KyrgyzOkupTushunuu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название теста"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание теста"
                    ),
                ),
            ],
            options={
                "verbose_name": "Кыргыз тил - Окуп тушунуу - Название теста",
                "verbose_name_plural": "Кыргыз тил - Окуп тушунуу - Название теста",
            },
        ),
        migrations.CreateModel(
            name="KyrgyzOkupTushunuuQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="Вопрос")),
            ],
            options={
                "verbose_name": "Окуп тушунуу - Вопрос",
                "verbose_name_plural": "Окуп тушунуу - Вопросы",
            },
        ),
        migrations.CreateModel(
            name="Kyrgyz1TestContent",
            fields=[],
            options={
                "verbose_name": "Кыргыз Тил - Аналогия",
                "verbose_name_plural": "Кыргыз Тил - Аналогия",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("OrtTest.testcontent",),
        ),
        migrations.CreateModel(
            name="Kyrgyz3TestContent",
            fields=[],
            options={
                "verbose_name": "Кыргыз Тил - Грамматика",
                "verbose_name_plural": "Кыргыз Тил - Грамматика",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("OrtTest.testcontent",),
        ),
        migrations.CreateModel(
            name="Math1TestContent",
            fields=[],
            options={
                "verbose_name": "Математика 1 Болум",
                "verbose_name_plural": "Математика 1 Болум",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("OrtTest.testcontent",),
        ),
        migrations.CreateModel(
            name="Math2TestContent",
            fields=[],
            options={
                "verbose_name": "Математика 2 Болум",
                "verbose_name_plural": "Математика 2 Болум",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("OrtTest.testcontent",),
        ),
        migrations.CreateModel(
            name="KyrgyzOkupTushunuuAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[("A", "A"), ("Б", "Б"), ("В", "В"), ("Г", "Г")],
                        max_length=1,
                        verbose_name="Вариант ответа",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Правильный ответ"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="OrtTest.kyrgyzokuptushunuuquestion",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Окуп тушунуу - Ответ",
                "verbose_name_plural": "Окуп тушунуу - Ответы",
            },
        ),
        migrations.CreateModel(
            name="KyrgyzOkupTushunuuText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Текст")),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="texts",
                        to="OrtTest.kyrgyzokuptushunuu",
                        verbose_name="Тест",
                    ),
                ),
            ],
            options={
                "verbose_name": "Окуп тушунуу - Текст",
                "verbose_name_plural": "Окуп тушунуу - Текст",
            },
        ),
        migrations.AddField(
            model_name="kyrgyzokuptushunuuquestion",
            name="text",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="OrtTest.kyrgyzokuptushunuutext",
                verbose_name="Текст",
            ),
        ),
    ]
