# Generated by Django 5.1.4 on 2025-01-03 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrtTest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testdata',
            name='response_status',
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_vars', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1, verbose_name='Ответ')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrtTest.testdata', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserAnswerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('true_answer_count', models.PositiveIntegerField(default=0, verbose_name='Количество правельных ответов')),
                ('false_answer_count', models.PositiveIntegerField(default=0, verbose_name='Количество не правельных ответов')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrtTest.testdata', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Счет ответов',
                'verbose_name_plural': 'Счета ответов',
            },
        ),
    ]
