# Generated by Django 5.1.4 on 2025-01-03 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrtTest', '0002_remove_testdata_response_status_useranswer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='user',
        ),
    ]
