# Generated by Django 5.1.4 on 2025-01-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrtTest", "0002_kyrgyzokuptushunuu_kyrgyzokuptushunuuquestion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kyrgyzokuptushunuuquestion",
            name="last_update_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Последнее обновление"
            ),
        ),
        migrations.AddField(
            model_name="kyrgyzokuptushunuuquestion",
            name="question_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Номер вопроса"
            ),
        ),
        migrations.AddField(
            model_name="kyrgyzokuptushunuuquestion",
            name="true_answer",
            field=models.CharField(
                choices=[("а", "А"), ("б", "Б"), ("в", "В"), ("г", "Г")],
                default=False,
                max_length=10,
                verbose_name="Правильный ответ",
            ),
        ),
        migrations.AddField(
            model_name="kyrgyzokuptushunuuquestion",
            name="var_A_text",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Вариант ответа 'А' (В текстовом варианте)",
            ),
        ),
        migrations.AddField(
            model_name="kyrgyzokuptushunuuquestion",
            name="var_B_text",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Вариант ответа 'Б' (В текстовом варианте)",
            ),
        ),
        migrations.AddField(
            model_name="kyrgyzokuptushunuuquestion",
            name="var_C_text",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Вариант ответа 'В' (В текстовом варианте)",
            ),
        ),
        migrations.AddField(
            model_name="kyrgyzokuptushunuuquestion",
            name="var_D_text",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Вариант ответа 'Г' (В текстовом варианте)",
            ),
        ),
        migrations.AddField(
            model_name="kyrgyzokuptushunuutext",
            name="text_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Номер вопроса"
            ),
        ),
        migrations.AlterField(
            model_name="kyrgyzokuptushunuuquestion",
            name="question_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Вопрос в текстовом формате"
            ),
        ),
        migrations.DeleteModel(
            name="KyrgyzOkupTushunuuAnswer",
        ),
    ]
