# Generated by Django 5.1.4 on 2025-01-03 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrtTest', '0005_useranswer_unique_user_test_answer'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='useranswer',
            name='unique_user_test_answer',
        ),
        migrations.AddField(
            model_name='additionalinstruction',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='additionalinstruction',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='test',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcategory',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testdata',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testdata',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testfulldescription',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testfulldescription',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testinstruction',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testinstruction',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useranswer',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='useranswercount',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useranswercount',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
