# Generated by Django 5.1.4 on 2025-01-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrtTest', '0006_remove_useranswer_unique_user_test_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='ooutput_time',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
