# Generated by Django 5.1.4 on 2025-01-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrtTest', '0007_useranswer_ooutput_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testdata',
            name='first_test',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='ooutput_time',
        ),
        migrations.AddField(
            model_name='test',
            name='first_test',
            field=models.BooleanField(default=False, verbose_name='Обозночение бедет ли тест первым бесплатным тестом'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='output_time',
            field=models.PositiveIntegerField(default=1, verbose_name='Время ответа (в секундах)'),
        ),
        migrations.AlterField(
            model_name='additionalinstruction',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='additionalinstruction',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='test',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='test',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='testcategory',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='testcategory',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='testfulldescription',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='testfulldescription',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='testinstruction',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='testinstruction',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='useranswercount',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='useranswercount',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
    ]
