# Generated by Django 5.1.4 on 2025-01-04 10:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrtTest', '0008_remove_testdata_first_test_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAnswerCount',
            new_name='UserStatistic',
        ),
    ]
