# Generated by Django 5.1.4 on 2025-01-04 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrtTest', '0009_rename_useranswercount_userstatistic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatistic',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrtTest.test', verbose_name='Тест'),
        ),
        migrations.AlterUniqueTogether(
            name='userstatistic',
            unique_together={('test', 'user')},
        ),
    ]
