# Generated by Django 5.1.4 on 2025-01-04 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrtTest', '0010_alter_userstatistic_test_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userstatistic',
            unique_together=set(),
        ),
    ]
