# Generated by Django 5.1.4 on 2025-01-04 11:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrtTest', '0011_alter_userstatistic_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userstatistic',
            unique_together={('test', 'user')},
        ),
    ]
