# Generated by Django 5.1.4 on 2025-01-04 12:16

import apps.OrtTest.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrtTest', '0012_alter_userstatistic_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('var_A', models.ImageField(upload_to=apps.OrtTest.models.upload_to_test, verbose_name="Вариант ответа 'A'")),
                ('var_B', models.ImageField(upload_to=apps.OrtTest.models.upload_to_test, verbose_name="Вариант ответа 'B'")),
                ('var_C', models.ImageField(upload_to=apps.OrtTest.models.upload_to_test, verbose_name="Вариант ответа 'C'")),
                ('var_D', models.ImageField(upload_to=apps.OrtTest.models.upload_to_test, verbose_name="Вариант ответа 'D'")),
                ('true_answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=10, verbose_name='Правельный ответ')),
                ('timer', models.PositiveIntegerField(verbose_name='Таймер (в секундах)')),
                ('last_update_date', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrtTest.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Данные теста',
                'verbose_name_plural': 'Данные теста',
            },
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrtTest.testcontent', verbose_name='Тест'),
        ),
        migrations.DeleteModel(
            name='TestData',
        ),
    ]
