# Generated by Django 5.1.4 on 2025-01-04 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrtTest', '0013_testcontent_alter_useranswer_test_delete_testdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatistic',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrtTest.testcontent', verbose_name='Тест'),
        ),
    ]
