# Generated by Django 5.1.4 on 2025-01-04 12:37

import apps.OrtTest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrtTest', '0014_alter_userstatistic_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testfulldescription',
            options={'verbose_name': 'Подробное описание теста', 'verbose_name_plural': 'Подробные описания тестов'},
        ),
        migrations.AlterUniqueTogether(
            name='userstatistic',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='test',
            name='first_test',
            field=models.BooleanField(default=False, verbose_name='Обозначение будет ли тест первым бесплатным'),
        ),
        migrations.AlterField(
            model_name='testcontent',
            name='true_answer',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=10, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='testcontent',
            name='var_A',
            field=models.ImageField(upload_to=apps.OrtTest.models.upload_to_test, verbose_name='Вариант ответа A'),
        ),
        migrations.AlterField(
            model_name='testcontent',
            name='var_B',
            field=models.ImageField(upload_to=apps.OrtTest.models.upload_to_test, verbose_name='Вариант ответа B'),
        ),
        migrations.AlterField(
            model_name='testcontent',
            name='var_C',
            field=models.ImageField(upload_to=apps.OrtTest.models.upload_to_test, verbose_name='Вариант ответа C'),
        ),
        migrations.AlterField(
            model_name='testcontent',
            name='var_D',
            field=models.ImageField(upload_to=apps.OrtTest.models.upload_to_test, verbose_name='Вариант ответа D'),
        ),
        migrations.AlterField(
            model_name='userstatistic',
            name='false_answer_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество неправильных ответов'),
        ),
        migrations.AlterField(
            model_name='userstatistic',
            name='true_answer_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество правильных ответов'),
        ),
    ]
