# Generated by Django 5.1.4 on 2025-01-04 13:02

import apps.OrtTest.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrtTest', '0015_alter_testfulldescription_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalinstruction',
            old_name='testing_instruction_FK',
            new_name='testing_instruction',
        ),
        migrations.AlterField(
            model_name='test',
            name='first_test',
            field=models.BooleanField(default=False, verbose_name='Обозначение будет ли тест первым бесплатным тестом'),
        ),
        migrations.AlterField(
            model_name='testcontent',
            name='var_A',
            field=models.ImageField(upload_to=apps.OrtTest.models.upload_to_test, verbose_name="Вариант ответа 'A'"),
        ),
        migrations.AlterField(
            model_name='testcontent',
            name='var_B',
            field=models.ImageField(upload_to=apps.OrtTest.models.upload_to_test, verbose_name="Вариант ответа 'B'"),
        ),
        migrations.AlterField(
            model_name='testcontent',
            name='var_C',
            field=models.ImageField(upload_to=apps.OrtTest.models.upload_to_test, verbose_name="Вариант ответа 'C'"),
        ),
        migrations.AlterField(
            model_name='testcontent',
            name='var_D',
            field=models.ImageField(upload_to=apps.OrtTest.models.upload_to_test, verbose_name="Вариант ответа 'D'"),
        ),
        migrations.AlterUniqueTogether(
            name='userstatistic',
            unique_together={('test', 'user')},
        ),
    ]
