# Generated by Django 5.1.4 on 2025-01-05 21:18

import apps.OrtTest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrtTest', '0018_alter_testcontent_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcontent',
            name='var_A',
        ),
        migrations.RemoveField(
            model_name='testcontent',
            name='var_B',
        ),
        migrations.RemoveField(
            model_name='testcontent',
            name='var_C',
        ),
        migrations.RemoveField(
            model_name='testcontent',
            name='var_D',
        ),
        migrations.AddField(
            model_name='testcontent',
            name='var_A_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.OrtTest.models.upload_to_test, verbose_name="Вариант ответа 'A' (В файловом варианте)"),
        ),
        migrations.AddField(
            model_name='testcontent',
            name='var_A_text',
            field=models.TextField(blank=True, null=True, verbose_name="Вариант ответа 'A' (В текстовом варианте)"),
        ),
        migrations.AddField(
            model_name='testcontent',
            name='var_B_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.OrtTest.models.upload_to_test, verbose_name="Вариант ответа 'B' (В файловом варианте)"),
        ),
        migrations.AddField(
            model_name='testcontent',
            name='var_B_text',
            field=models.TextField(blank=True, null=True, verbose_name="Вариант ответа 'B' (В текстовом варианте)"),
        ),
        migrations.AddField(
            model_name='testcontent',
            name='var_C_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.OrtTest.models.upload_to_test, verbose_name="Вариант ответа 'C' (В файловом варианте)"),
        ),
        migrations.AddField(
            model_name='testcontent',
            name='var_C_text',
            field=models.TextField(blank=True, null=True, verbose_name="Вариант ответа 'C' (В текстовом варианте)"),
        ),
        migrations.AddField(
            model_name='testcontent',
            name='var_D_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.OrtTest.models.upload_to_test, verbose_name="Вариант ответа 'D' (В файловом варианте)"),
        ),
        migrations.AddField(
            model_name='testcontent',
            name='var_D_text',
            field=models.TextField(blank=True, null=True, verbose_name="Вариант ответа 'D' (В текстовом варианте)"),
        ),
    ]
