# Generated by Django 5.1.4 on 2025-01-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrtTest', '0019_remove_testcontent_var_a_remove_testcontent_var_b_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcontent',
            name='question',
        ),
        migrations.RemoveField(
            model_name='testcontent',
            name='timer',
        ),
        migrations.AddField(
            model_name='testcontent',
            name='question_image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Вопрос в файловом формате'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcontent',
            name='question_text',
            field=models.TextField(default=1, verbose_name='Вопрос в текстовом формате'),
            preserve_default=False,
        ),
    ]
