# Generated by Django 5.1.4 on 2025-01-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrtTest', '0020_remove_testcontent_question_remove_testcontent_timer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': '2. Тесты'},
        ),
        migrations.AlterModelOptions(
            name='testcategory',
            options={'verbose_name': 'Категория теста', 'verbose_name_plural': '1. Категории тестов'},
        ),
        migrations.AlterModelOptions(
            name='testcontent',
            options={'verbose_name': 'Вопрос теста', 'verbose_name_plural': '3. Вопросы тестов'},
        ),
        migrations.AlterModelOptions(
            name='testfulldescription',
            options={'verbose_name': 'Подробное описание теста', 'verbose_name_plural': '4. Подробные описания тестов'},
        ),
        migrations.AlterModelOptions(
            name='testinstruction',
            options={'verbose_name': 'Инструкция теста', 'verbose_name_plural': '5. Инструкции тестов'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'Ответ пользователя', 'verbose_name_plural': '6. Ответы пользователей'},
        ),
        migrations.AlterModelOptions(
            name='userstatistic',
            options={'verbose_name': 'Счет ответов', 'verbose_name_plural': '7. Счета ответов'},
        ),
        migrations.AddField(
            model_name='testcontent',
            name='additional_questions',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительный текст к вопросу'),
        ),
        migrations.AlterField(
            model_name='testcontent',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Вопрос в файловом формате'),
        ),
        migrations.AlterField(
            model_name='testcontent',
            name='question_text',
            field=models.TextField(blank=True, null=True, verbose_name='Вопрос в текстовом формате'),
        ),
        migrations.DeleteModel(
            name='AdditionalInstruction',
        ),
    ]
