# Generated by Django 5.1.4 on 2025-01-18 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrtTest', '0021_alter_test_options_alter_testcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcontent',
            options={'verbose_name': 'Вопрос теста', 'verbose_name_plural': '5. Вопросы тестов'},
        ),
        migrations.AlterModelOptions(
            name='testfulldescription',
            options={'verbose_name': 'Подробное описание теста', 'verbose_name_plural': '3. Подробные описания тестов'},
        ),
        migrations.AlterModelOptions(
            name='testinstruction',
            options={'verbose_name': 'Инструкция теста', 'verbose_name_plural': '4. Инструкции тестов'},
        ),
    ]
