# Generated by Django 5.1.4 on 2025-01-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("OrtTest", "0022_alter_testcontent_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestInstruction",
        ),
    ]
