# Generated by Django 5.1.4 on 2025-01-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrtTest", "0023_delete_testinstruction"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcontent",
            name="question_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Номер вопроса"
            ),
        ),
    ]
