# Generated by Django 5.1.4 on 2025-01-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("OrtTest", "0024_testcontent_question_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kyrgyz1TestContent",
            fields=[],
            options={
                "verbose_name": "Kyrgyz Language 1 Question",
                "verbose_name_plural": "Kyrgyz Language 1 Questions",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("OrtTest.testcontent",),
        ),
        migrations.CreateModel(
            name="Kyrgyz2TestContent",
            fields=[],
            options={
                "verbose_name": "Kyrgyz Language 2 Question",
                "verbose_name_plural": "Kyrgyz Language 2 Questions",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("OrtTest.testcontent",),
        ),
        migrations.CreateModel(
            name="Kyrgyz3TestContent",
            fields=[],
            options={
                "verbose_name": "Kyrgyz Language 3 Question",
                "verbose_name_plural": "Kyrgyz Language 3 Questions",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("OrtTest.testcontent",),
        ),
        migrations.CreateModel(
            name="Math1TestContent",
            fields=[],
            options={
                "verbose_name": "Math 1 Question",
                "verbose_name_plural": "Math 1 Questions",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("OrtTest.testcontent",),
        ),
        migrations.CreateModel(
            name="Math2TestContent",
            fields=[],
            options={
                "verbose_name": "Math 2 Question",
                "verbose_name_plural": "Math 2 Questions",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("OrtTest.testcontent",),
        ),
    ]
