# Generated by Django 5.1.4 on 2025-01-19 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("OrtTest", "0025_kyrgyz1testcontent_kyrgyz2testcontent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kyrgyz1UserAnswer",
            fields=[],
            options={
                "verbose_name": "Ответы пользователей - Кыргыз Тил - Аналогия",
                "verbose_name_plural": "Ответы пользователей - Кыргыз Тил - Аналогия",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("OrtTest.useranswer",),
        ),
        migrations.CreateModel(
            name="Kyrgyz2UserAnswer",
            fields=[],
            options={
                "verbose_name": "Ответы пользователей - Кыргыз Тил - Окуу жана тушунуу",
                "verbose_name_plural": "Ответы пользователей - Кыргыз Тил - Окуу жана тушунуу",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("OrtTest.useranswer",),
        ),
        migrations.CreateModel(
            name="Kyrgyz3UserAnswer",
            fields=[],
            options={
                "verbose_name": "Ответы пользователей - Кыргыз Тил - Грамматика",
                "verbose_name_plural": "Ответы пользователей - Кыргыз Тил - Грамматика",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("OrtTest.useranswer",),
        ),
        migrations.CreateModel(
            name="Math1UserAnswer",
            fields=[],
            options={
                "verbose_name": "Ответы пользователей - Математика 1",
                "verbose_name_plural": "Ответы пользователей - Математика 1",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("OrtTest.useranswer",),
        ),
        migrations.CreateModel(
            name="Math2UserAnswer",
            fields=[],
            options={
                "verbose_name": "Ответы пользователей - Математика 2",
                "verbose_name_plural": "Ответы пользователей - Математика 2",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("OrtTest.useranswer",),
        ),
        migrations.AlterModelOptions(
            name="kyrgyz1testcontent",
            options={
                "verbose_name": "Кыргыз Тил - Аналогия",
                "verbose_name_plural": "Кыргыз Тил - Аналогия",
            },
        ),
        migrations.AlterModelOptions(
            name="kyrgyz2testcontent",
            options={
                "verbose_name": "Кыргыз Тил - Окуу жана тушунуу",
                "verbose_name_plural": "Кыргыз Тил - Окуу жана тушунуу",
            },
        ),
        migrations.AlterModelOptions(
            name="kyrgyz3testcontent",
            options={
                "verbose_name": "Кыргыз Тил - Грамматика",
                "verbose_name_plural": "Кыргыз Тил - Грамматика",
            },
        ),
        migrations.AlterModelOptions(
            name="math1testcontent",
            options={
                "verbose_name": "Математика 1 Болум",
                "verbose_name_plural": "Математика 1 Болум",
            },
        ),
        migrations.AlterModelOptions(
            name="math2testcontent",
            options={
                "verbose_name": "Математика 2 Болум",
                "verbose_name_plural": "Математика 2 Болум",
            },
        ),
    ]
