# Generated by Django 5.1.4 on 2025-01-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrtTest", "0027_alter_testcontent_true_answer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useranswer",
            name="output_time",
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="answer_vars",
            field=models.CharField(
                choices=[("а", "А"), ("б", "Б"), ("в", "В"), ("г", "Г")],
                max_length=1,
                verbose_name="Ответ студента",
            ),
        ),
    ]
