# Generated by Django 5.1.4 on 2025-01-19 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrtTest", "0028_remove_useranswer_output_time_and_more"),
        ("users", "0004_alter_user_user_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstatistic",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.mockassessmenttest",
                verbose_name="Пользователь",
            ),
        ),
    ]
