# Generated by Django 5.1.4 on 2025-01-19 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrtTest", "0029_alter_userstatistic_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="Kyrgyz1UserAnswer",
        ),
        migrations.DeleteModel(
            name="Kyrgyz2UserAnswer",
        ),
        migrations.DeleteModel(
            name="Kyrgyz3UserAnswer",
        ),
        migrations.DeleteModel(
            name="Math1UserAnswer",
        ),
        migrations.DeleteModel(
            name="Math2UserAnswer",
        ),
        migrations.AlterField(
            model_name="userstatistic",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
