# Generated by Django 5.1.4 on 2025-01-23 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrtTest', '0030_delete_kyrgyz1useranswer_delete_kyrgyz2useranswer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_category_name', models.CharField(max_length=52, verbose_name='Название типа теста')),
                ('last_update_date', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория теста',
                'verbose_name_plural': '2. Категории тестов',
            },
        ),
        migrations.DeleteModel(
            name='Kyrgyz1TestContent',
        ),
        migrations.DeleteModel(
            name='Kyrgyz2TestContent',
        ),
        migrations.DeleteModel(
            name='Kyrgyz3TestContent',
        ),
        migrations.DeleteModel(
            name='Math1TestContent',
        ),
        migrations.DeleteModel(
            name='Math2TestContent',
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': '3. Тесты'},
        ),
        migrations.AlterModelOptions(
            name='testcontent',
            options={'verbose_name': 'Вопрос теста', 'verbose_name_plural': '6. Вопросы тестов'},
        ),
        migrations.AlterModelOptions(
            name='testfulldescription',
            options={'verbose_name': 'Подробное описание теста', 'verbose_name_plural': '4. Подробные описания тестов'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'Ответ пользователя', 'verbose_name_plural': '7. Ответы пользователей'},
        ),
        migrations.AlterModelOptions(
            name='userstatistic',
            options={'verbose_name': 'Счет ответов', 'verbose_name_plural': '8. Счета ответов'},
        ),
        migrations.AddField(
            model_name='test',
            name='subject_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='OrtTest.subjectcategory', verbose_name='Категория предмета'),
            preserve_default=False,
        ),
    ]
