# Generated by Django 5.1.4 on 2025-01-23 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("OrtTest", "0004_alter_kyrgyzokuptushunuutext_text_number"),
        ("OrtTest", "0031_subjectcategory_delete_kyrgyz1testcontent_and_more"),
    ]

    operations = []
