# Generated by Django 5.1.4 on 2025-01-23 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrtTest", "0032_merge_20250123_1809"),
    ]

    operations = [
        migrations.CreateModel(
            name="OkupTushunuu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Default Title",
                        max_length=255,
                        verbose_name="Название теста",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание теста")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Окуп тушунуу",
                "verbose_name_plural": "Окуп тушунуу",
            },
        ),
        migrations.CreateModel(
            name="OkupTushunuuQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Номер вопроса"
                    ),
                ),
                (
                    "question_text",
                    models.TextField(
                        default="Default question text", verbose_name="Вопрос"
                    ),
                ),
                (
                    "var_A_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Вариант ответа 'А'"
                    ),
                ),
                (
                    "var_B_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Вариант ответа 'Б'"
                    ),
                ),
                (
                    "var_C_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Вариант ответа 'В'"
                    ),
                ),
                (
                    "var_D_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Вариант ответа 'Г'"
                    ),
                ),
                (
                    "true_answer",
                    models.CharField(
                        choices=[("а", "А"), ("б", "Б"), ("в", "В"), ("г", "Г")],
                        default="а",
                        max_length=10,
                        verbose_name="Правильный ответ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос Окуп тушунуу",
                "verbose_name_plural": "Вопросы Окуп тушунуу",
            },
        ),
        migrations.CreateModel(
            name="OkupTushunuuText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Номер вопроса"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Default Title",
                        max_length=255,
                        verbose_name="Название текста",
                    ),
                ),
                (
                    "text_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="okup_tushunuu_files/",
                        verbose_name="Файл текста",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="texts",
                        to="OrtTest.okuptushunuu",
                        verbose_name="Тест",
                    ),
                ),
            ],
            options={
                "verbose_name": "Текст - Окуп тушунуу",
                "verbose_name_plural": "Тексты - Окуп тушунуу",
            },
        ),
        migrations.RemoveField(
            model_name="kyrgyzokuptushunuutext",
            name="test",
        ),
        migrations.RemoveField(
            model_name="kyrgyzokuptushunuuquestion",
            name="text",
        ),
        migrations.DeleteModel(
            name="Kyrgyz1TestContent",
        ),
        migrations.DeleteModel(
            name="Kyrgyz3TestContent",
        ),
        migrations.DeleteModel(
            name="Math1TestContent",
        ),
        migrations.DeleteModel(
            name="Math2TestContent",
        ),
        migrations.AddField(
            model_name="userstatistic",
            name="okup_tushunuu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="OrtTest.okuptushunuu",
                verbose_name="Окуп тушунуу",
            ),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="okup_tushunuu_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="OrtTest.okuptushunuuquestion",
                verbose_name="Вопрос Окуп Тушунуу",
            ),
        ),
        migrations.AddField(
            model_name="okuptushunuuquestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="OrtTest.okuptushunuutext",
                verbose_name="Текст",
            ),
        ),
        migrations.DeleteModel(
            name="KyrgyzOkupTushunuu",
        ),
        migrations.DeleteModel(
            name="KyrgyzOkupTushunuuQuestion",
        ),
        migrations.DeleteModel(
            name="KyrgyzOkupTushunuuText",
        ),
    ]
