# Generated by Django 5.1.4 on 2025-01-27 11:20

import apps.OrtTest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrtTest', '0034_alter_okuptushunuu_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='okuptushunuuquestion',
            options={'verbose_name': 'Вопрос Окуп тушунуу', 'verbose_name_plural': '8. Вопросы Окуп тушунуу'},
        ),
        migrations.AlterModelOptions(
            name='okuptushunuutext',
            options={'verbose_name': 'Текст - Окуп тушунуу', 'verbose_name_plural': '7. Тексты - Окуп тушунуу'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'Ответ пользователя', 'verbose_name_plural': '9. Ответы пользователей'},
        ),
        migrations.AlterModelOptions(
            name='userstatistic',
            options={'verbose_name': 'Счет ответов', 'verbose_name_plural': '10. Счета ответов'},
        ),
        migrations.AddField(
            model_name='testcontent',
            name='var_E_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.OrtTest.models.upload_to_test, verbose_name="Вариант ответа 'Д' (В файловом варианте)"),
        ),
        migrations.AddField(
            model_name='testcontent',
            name='var_E_text',
            field=models.TextField(blank=True, null=True, verbose_name="Вариант ответа 'Д' (В текстовом варианте)"),
        ),
        migrations.AlterField(
            model_name='testcontent',
            name='true_answer',
            field=models.CharField(choices=[('а', 'А'), ('б', 'Б'), ('в', 'В'), ('г', 'Г'), ('д', 'Д')], max_length=10, verbose_name='Правильный ответ'),
        ),
    ]
