# Generated by Django 5.1.4 on 2025-01-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrtTest', '0035_alter_okuptushunuuquestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='okuptushunuuquestion',
            name='var_E_text',
            field=models.TextField(blank=True, null=True, verbose_name="Вариант ответа 'Д'"),
        ),
        migrations.AlterField(
            model_name='okuptushunuuquestion',
            name='true_answer',
            field=models.CharField(choices=[('а', 'А'), ('б', 'Б'), ('в', 'В'), ('г', 'Г'), ('д', 'Д')], default='а', max_length=10, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer_vars',
            field=models.CharField(choices=[('а', 'А'), ('б', 'Б'), ('в', 'В'), ('г', 'Г'), ('д', 'Д')], max_length=1, verbose_name='Ответ студента'),
        ),
    ]
