# Generated by Django 5.1.4 on 2025-02-03 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrtTest', '0036_okuptushunuuquestion_var_e_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='okuptushunuuquestion',
            name='okup_tushunuu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='OrtTest.okuptushunuu', verbose_name='Окуп тушунуу'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='okuptushunuuquestion',
            name='okup_tushunuu_text',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='OrtTest.okuptushunuutext', verbose_name='Окуп тушунуу текст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testfulldescription',
            name='description',
            field=models.ImageField(upload_to='TestFullDescription/', verbose_name='Описаниев в формате изображения'),
        ),
    ]
