# Generated by Django 5.1.4 on 2025-02-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrtTest", "0036_okuptushunuuquestion_var_e_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="okuptushunuutext",
            name="text_file",
        ),
        migrations.AddField(
            model_name="okuptushunuutext",
            name="text1",
            field=models.ImageField(blank=True, null=True, upload_to="okup_tushunuu/"),
        ),
        migrations.AddField(
            model_name="okuptushunuutext",
            name="text2",
            field=models.ImageField(blank=True, null=True, upload_to="okup_tushunuu/"),
        ),
        migrations.AddField(
            model_name="okuptushunuutext",
            name="text3",
            field=models.ImageField(blank=True, null=True, upload_to="okup_tushunuu/"),
        ),
        migrations.AddField(
            model_name="okuptushunuutext",
            name="text4",
            field=models.ImageField(blank=True, null=True, upload_to="okup_tushunuu/"),
        ),
        migrations.AddField(
            model_name="okuptushunuutext",
            name="text5",
            field=models.ImageField(blank=True, null=True, upload_to="okup_tushunuu/"),
        ),
        migrations.AddField(
            model_name="okuptushunuutext",
            name="text6",
            field=models.ImageField(blank=True, null=True, upload_to="okup_tushunuu/"),
        ),
        migrations.AddField(
            model_name="okuptushunuutext",
            name="text7",
            field=models.ImageField(blank=True, null=True, upload_to="okup_tushunuu/"),
        ),
    ]
