# Generated by Django 5.1.4 on 2025-02-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrtTest', '0037_okuptushunuuquestion_okup_tushunuu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testfulldescription',
            old_name='description',
            new_name='description_image',
        ),
        migrations.RemoveField(
            model_name='okuptushunuuquestion',
            name='okup_tushunuu_text',
        ),
        migrations.RemoveField(
            model_name='okuptushunuutext',
            name='text_file',
        ),
        migrations.AddField(
            model_name='okuptushunuutext',
            name='text1',
            field=models.ImageField(blank=True, null=True, upload_to='okup_tushunuu/'),
        ),
        migrations.AddField(
            model_name='okuptushunuutext',
            name='text2',
            field=models.ImageField(blank=True, null=True, upload_to='okup_tushunuu/'),
        ),
        migrations.AddField(
            model_name='okuptushunuutext',
            name='text3',
            field=models.ImageField(blank=True, null=True, upload_to='okup_tushunuu/'),
        ),
        migrations.AddField(
            model_name='okuptushunuutext',
            name='text4',
            field=models.ImageField(blank=True, null=True, upload_to='okup_tushunuu/'),
        ),
        migrations.AddField(
            model_name='okuptushunuutext',
            name='text5',
            field=models.ImageField(blank=True, null=True, upload_to='okup_tushunuu/'),
        ),
        migrations.AddField(
            model_name='okuptushunuutext',
            name='text6',
            field=models.ImageField(blank=True, null=True, upload_to='okup_tushunuu/'),
        ),
        migrations.AddField(
            model_name='okuptushunuutext',
            name='text7',
            field=models.ImageField(blank=True, null=True, upload_to='okup_tushunuu/'),
        ),
        migrations.AlterField(
            model_name='testcontent',
            name='question_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядковый номер вопроса'),
        ),
    ]
