# Generated by Django 5.1.4 on 2025-02-03 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrtTest', '0038_rename_description_testfulldescription_description_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='okuptushunuu',
            options={'verbose_name': 'Окуп тушунуу', 'verbose_name_plural': '6. Окуп тушунуу'},
        ),
        migrations.AlterModelOptions(
            name='okuptushunuuquestion',
            options={'verbose_name': 'Вопрос Окуп тушунуу', 'verbose_name_plural': '9. Вопросы Окуп тушунуу'},
        ),
        migrations.AlterModelOptions(
            name='okuptushunuutext',
            options={'verbose_name': 'Текст - Окуп тушунуу', 'verbose_name_plural': '8. Тексты - Окуп тушунуу'},
        ),
        migrations.AlterModelOptions(
            name='userstatistic',
            options={'verbose_name': 'Счет ответов', 'verbose_name_plural': '9. Счета ответов'},
        ),
        migrations.RemoveField(
            model_name='testfulldescription',
            name='test_category',
        ),
        migrations.AddField(
            model_name='testfulldescription',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='OrtTest.test', verbose_name='Тест'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TestInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_title', models.CharField(max_length=60, verbose_name='Название описания')),
                ('instruction_image', models.ImageField(upload_to='TestInstruction/', verbose_name='Описаниев в формате изображения')),
                ('last_update_date', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrtTest.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': '5. Инструкция тестов',
                'verbose_name_plural': '5. Инструкции тестов',
            },
        ),
    ]
