# Generated by Django 5.1.4 on 2025-02-04 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrtTest', '0039_alter_okuptushunuu_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okuptushunuutext',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='OrtTest.test', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='testcategory',
            name='test_category_name',
            field=models.CharField(max_length=52, verbose_name='Название типа предмета'),
        ),
        migrations.AlterField(
            model_name='testinstruction',
            name='instruction_image',
            field=models.ImageField(blank=True, null=True, upload_to='TestInstruction/', verbose_name='Описаниев в формате изображения'),
        ),
    ]
