# Generated by Django 5.1.4 on 2025-02-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrtTest', '0040_alter_okuptushunuutext_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatistic',
            name='accuracy_percentage',
            field=models.FloatField(default=0.0, verbose_name='Процент правильных ответов'),
        ),
    ]
