# Generated by Django 5.1.4 on 2025-02-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MockAssessmentTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockassessmentuser',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, verbose_name='Номер телефона'),
        ),
    ]
