# Generated by Django 5.1.4 on 2025-01-11 18:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=55, validators=[django.core.validators.RegexValidator(message='Введите правильный номер телефона', regex='^(0\\d{9}|\\+996\\d{9})$')], verbose_name='Номер телефона')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('image', models.ImageField(upload_to='graduates/images', verbose_name='Фотография')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(245)], verbose_name='Баллы')),
                ('review', models.TextField(verbose_name='Отзыв')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Выпускник',
                'verbose_name_plural': 'Выпускники',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название предмета')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=55, verbose_name='Фамилия')),
                ('image', models.ImageField(upload_to='teachers/images', verbose_name='Фотография')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AboutStaffStudents.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['-created_at'],
            },
        ),
    ]
