# Generated by Django 5.1.4 on 2025-01-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutStaffStudents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='slug'),
        ),
    ]
