# Generated by Django 5.1.4 on 2025-01-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AboutStaffStudents", "0002_alter_feedback_slug_alter_graduate_slug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="graduate",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="slug",
        ),
    ]
