# Generated by Django 5.1.4 on 2025-01-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "AboutStaffStudents",
            "0003_remove_feedback_slug_remove_graduate_slug_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AddField(
            model_name="graduate",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="slug"
            ),
        ),
    ]
