name: CI/CD Pipeline

on:
  push:
    branches:
      - Test-CD/CI-Pipeline-Aktan

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy application
        run: |
          echo "Deployment steps here"
