name: CD/CI Pipeline

on:
  push:
    branches:
      - Test-CD/CI-Pipeline-Aktan

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Шаг для создания файла .env
    - name: Create .env file
      run: |
        echo DEBUG=${{ secrets.DEBUG }} >> .env
        echo DB_NAME=${{ secrets.DB_NAME }} >> .env
        echo DB_USER=${{ secrets.DB_USER }} >> .env
        echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
        echo DB_HOST=${{ secrets.DB_HOST }} >> .env
        echo DB_PORT=${{ secrets.DB_PORT }} >> .env

    # Запуск docker-compose
    - name: Build and run Docker containers
      run: docker-compose up --build -d
