name: CD/CI Pipeline

on:
  push:
    branches:
      - Test-CD/CI-Pipeline-Aktan
  pull_request:

jobs:
  test-build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.6-alpine
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5432:5432

    steps:
      # 1. Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Установка Docker Compose
      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose -y

      # 3. Сборка Docker Compose
      - name: Build and run services
        run: docker-compose up --build -d

      # 4. Прогон тестов
      - name: Run tests
        run: docker-compose run django python manage.py test
